#!/bin/zsh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_DIR="$SCRIPT_DIR"
REPO_DIR="${SM_TOOL_REPO_DIR:-$SCRIPT_DIR}"

export JIRA_URL="${JIRA_URL:-https://jira.company.net}"
export JIRA_AUTH="${JIRA_AUTH:-bearer}"
export JIRA_IMPORT_BUCKET="${JIRA_IMPORT_BUCKET:-jira-api}"
export JIRA_MAX_ISSUES="${JIRA_MAX_ISSUES:-2000}"
export NODE_USE_SYSTEM_CA=1

setup_node_ca() {
  if [[ "$(uname -s)" != "Darwin" ]] || ! command -v security >/dev/null 2>&1; then
    return
  fi

  local ca_bundle="${TMPDIR:-/tmp}/smtool-node-ca.pem"
  : > "$ca_bundle"

  security find-certificate -a -p /Library/Keychains/System.keychain >> "$ca_bundle" 2>/dev/null || true
  security find-certificate -a -p /System/Library/Keychains/SystemRootCertificates.keychain >> "$ca_bundle" 2>/dev/null || true
  security find-certificate -a -p "$HOME/Library/Keychains/login.keychain-db" >> "$ca_bundle" 2>/dev/null || true

  if [[ -s "$ca_bundle" ]]; then
    export NODE_EXTRA_CA_CERTS="$ca_bundle"
  fi
}

setup_node_ca

if [[ ! -f "$REPO_DIR/package.json" ]]; then
  echo "ScrumMasterTool repo was not found at: $REPO_DIR"
  echo "Set SM_TOOL_REPO_DIR to the local repo path and run this file again."
  exit 1
fi

if [[ -d "$WORKSPACE_DIR/teams" ]]; then
  TEAMS_DIR="$WORKSPACE_DIR/teams"
elif [[ -d "$WORKSPACE_DIR/Teams" ]]; then
  TEAMS_DIR="$WORKSPACE_DIR/Teams"
else
  echo "No teams folder found under: $WORKSPACE_DIR"
  exit 1
fi

TEAM_LIST="$(node - "$TEAMS_DIR" <<'NODE'
const fs = require("fs");
const path = require("path");
const teamsDir = process.argv[2];
function normalize(value) { return String(value || "").trim().toLowerCase(); }
function hasRealSavedJql(jiraQuery) {
  const queries = [...(jiraQuery?.queries || []), ...(jiraQuery?.issueQuery?.queries || [])];
  return queries.some((query) => {
    const jql = normalize(query?.jql);
    return jql.length > 0 && !jql.includes("yourproject");
  });
}
for (const entry of fs.readdirSync(teamsDir, { withFileTypes: true }).filter((item) => item.isDirectory()).sort((a, b) => a.name.localeCompare(b.name))) {
  const configPath = path.join(teamsDir, entry.name, "team.json");
  if (!fs.existsSync(configPath)) continue;
  const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
  const name = String(config.teamName || entry.name).replace(/[\t\r\n]+/g, " ").trim();
  console.log([entry.name, name, hasRealSavedJql(config.jiraQuery) ? "1" : "0"].join("\t"));
}
NODE
)"

if [[ -z "$TEAM_LIST" ]]; then
  echo "No teams with team.json found under: $TEAMS_DIR"
  exit 1
fi

TEAM_IDS=()
TEAM_NAMES=()
TEAM_HAS_JQL=()
index=1
echo "Select team to renew:"
while IFS=$'\t' read -r team_id team_name has_jql; do
  [[ -z "$team_id" ]] && continue
  TEAM_IDS+=("$team_id")
  TEAM_NAMES+=("$team_name")
  TEAM_HAS_JQL+=("$has_jql")
  printf "%2d) %s (%s)\n" "$index" "$team_name" "$team_id"
  index=$((index + 1))
done <<< "$TEAM_LIST"

echo "Enter one team number, multiple numbers separated by comma/space, or all."
echo -n "Team number(s): "
read -r selection
SELECTED_INDEXES=()
selection_normalized="$(echo "$selection" | tr "[:upper:]" "[:lower:]" | xargs)"
if [[ "$selection_normalized" == "all" ]]; then
  for ((i = 1; i <= ${#TEAM_IDS[@]}; i++)); do
    SELECTED_INDEXES+=("$i")
  done
else
  selection_tokens="${selection//,/ }"
  for token in ${(z)selection_tokens}; do
    if ! [[ "$token" =~ ^[0-9]+$ ]] || (( token < 1 || token > ${#TEAM_IDS[@]} )); then
      echo "Invalid team number: $token"
      exit 1
    fi
    SELECTED_INDEXES+=("$token")
  done
fi

if (( ${#SELECTED_INDEXES[@]} == 0 )); then
  echo "No team selected."
  exit 1
fi

for selection_index in "${SELECTED_INDEXES[@]}"; do
  TEAM_ID="${TEAM_IDS[$selection_index]}"
  HAS_SAVED_JQL="${TEAM_HAS_JQL[$selection_index]}"
  if [[ "$HAS_SAVED_JQL" != "1" ]]; then
    echo "No real saved JQL found in teams/${TEAM_ID}/team.json."
    echo "Add JQL in the app first, then run this file again."
    exit 1
  fi
done

if [[ -z "${JIRA_TOKEN:-}" ]]; then
  echo -n "Jira token: "
  read -rs JIRA_TOKEN
  echo
  export JIRA_TOKEN
fi

clear_generated_jira_exports() {
  local team_id="$1"
  local import_dir="$TEAMS_DIR/$team_id/imports/$JIRA_IMPORT_BUCKET"
  mkdir -p "$import_dir"

  # Jira API refresh is a current snapshot, not an append-only history.
  # Remove only files generated by this Jira pull flow; preserve manual imports.
  find "$import_dir" -maxdepth 1 -type f \( \
    -name 'issues.csv' -o \
    -name 'issues-*.csv' -o \
    -name 'time-in-status.csv' -o \
    -name 'time-in-status-*.csv' \
  \) -delete
}

for selection_index in "${SELECTED_INDEXES[@]}"; do
  TEAM_ID="${TEAM_IDS[$selection_index]}"
  TEAM_NAME="${TEAM_NAMES[$selection_index]}"
  echo "Renewing Jira data for ${TEAM_NAME} (${TEAM_ID})"

  clear_generated_jira_exports "$TEAM_ID"

  npm --prefix "$REPO_DIR" run jira:pull -- \
    --workspace "$WORKSPACE_DIR" \
    --team "$TEAM_ID" \
    --max "$JIRA_MAX_ISSUES" \
    --bucket "$JIRA_IMPORT_BUCKET"
done

npm --prefix "$REPO_DIR" run analyze -- --workspace "$WORKSPACE_DIR"

echo "Done. Press Enter to close."
read
